Repository acm-ucr/membership-portal, pull requests merged in 2022-11, with the labels that each got.

#158 added hover function
  components/AvailableForm.jsx
  components/CompletedForm.jsx
Labels: ready for review, forms

#160 fixed circle color bug
  components/Announcements.jsx
Labels: ready for review

#161 fixed overriding data
  pages/api/profile/setInfo.js
Labels: ready for review

#163 no resources messae
  components/Resources.jsx
Labels: ready for review, resources

#159 Made QR Code Button
  components/Photo.jsx
Labels: ready for review
