Repository acm-ucr/membership-portal, pull requests merged in 2023-06, with the labels that each got.

#419 Vertically Centered Error Message
  pages/invalid.js
Labels: repository

#418 Dashboard Shows Month and Year
  pages/_app.js
Labels: dashboard

#417 Increased Logout Button Padding
  components/Navigation.jsx
Labels: navigation

#415 Vraimondi04/tab names
  components/PDFViewer.jsx
  pages/calendar.js
  pages/dashboard.js
  pages/resume.js
Labels: repository

#420 Clubroom Spacing Reduced
  pages/clubroom.js
Labels: clubroom

#416 Removed Background in Clubroom
  components/Clubroom.jsx
Labels: clubroom

#428 Made calendar footprint smaller
  components/CustomToolbar.jsx
Labels: ready for review, calendar
