Repository acm-ucr/membership-portal, pull requests merged in 2023-01, with the labels that each got.

#185 fix margin
  components/MockInterviewForm.jsx
  components/MockInterviewFormDetails.jsx
  components/ResumeReviewForm.jsx
  components/ResumeReviewFormDetails.jsx
Labels: ready for review, mock interview, resume review

#184 fix nav width
  components/Navigation.jsx
Labels: ready for review, navigation

#183 fix profile width
  components/Profile.jsx
Labels: ready for review, profile

#182 Update README.md
  README.md
Labels: ready for review

#181 Change to use email from auth
  package-lock.json
  pages/api/profile/getInfo.js
Labels: ready for review, backend

#193 backend
  components/Announcement.jsx
  components/Announcements.jsx
  components/Home.jsx
  components/Navigation.jsx
  components/Photo.jsx
  components/Profile.jsx
  components/Resources.jsx
  next.config.js
  pages/api/get5Announcements.js
  pages/api/profile/getInfo.js
  pages/api/profile/setInfo.js
  pages/api/profile/verifyUser.js
  pages/index.js
  pages/user/profile.js
Labels: ready for review, backend

#195 Issue #190: added titles
  pages/user/dashboard.js
  pages/user/forms.js
  pages/user/profile.js
  pages/user/resources.js
Labels: ready for review, repository

#196 resized navbar
  components/Navigation.jsx
  package-lock.json
Labels: ready for review, navigation

#197 Issue 191: Same Size Headers
  components/Announcements.jsx
  components/Meeting.jsx
  components/Meetings.jsx
Labels: ready for review, dashboard

#207 Footprint
  components/Home.jsx
Labels: ready for review, dashboard
