Repository acm-ucr/membership-portal, pull requests merged in 2023-04, with the labels that each got.

#269 Vraimondi04/google calendar
  components/Calendar.jsx
  components/CustomEvent.jsx
  components/Modal.jsx
  components/data/Events.jsx
  components/data/Filters.jsx
Labels: backend, calendar

#271 update sizing in edit profile + tailwind engineering for dashboard
  components/Profile.jsx
  pages/dashboard.js
Labels: ready for review, dashboard, profile

#272 updated firebase backend call for resources
  components/Profile.jsx
  components/TimeFilter.jsx
  pages/api/getAllResources.js
Labels: ready for review, resources, backend

#287 fixed slice of events from calendar api call
  pages/dashboard.js
Labels: ready for review, dashboard, backend, calendar

#289 updated cloudbuild.yaml to inject new env variables for google sheet
  cloudbuild.yaml
Labels: ready for review, backend

#302 Aligned welcome message
  components/Home.jsx
Labels: ready for review, dashboard

#301 Implement Resource Context
  components/ApplicationProfile.jsx
  components/ResourceContext.jsx
  components/Resources.jsx
  pages/_app.js
Labels: ready for review, resources

#300 Ensure image renders once image prop is loaded
  components/ApplicationProfile.jsx
Labels: ready for review, register

#303 deleted creds filder
  creds/placeholder.txt
Labels: repository

#304 Redirect to prevent verified members from accessing apply page
  components/ApplicationProfile.jsx
  pages/invalidRequest.js
Labels: ready for review, register

#305 Removed Validate Year Function
  components/Profile.jsx
Labels: profile, repository

#306 Removed Unused Image
  public/acmucr.png
Labels: repository

#307 Add Clubroom Info
  components/Clubroom.jsx
  components/Frame.jsx
  pages/clubroom.js
Labels: dashboard

#308 statically imported image
  components/Navigation.jsx
Labels: navigation

#320 Add Build Check
  .github/workflows/pull_request.yaml
Labels: repository
