Repository acm-ucr/membership-portal, pull requests merged in 2023-02, with the labels that each got.

#213 Safe duck/fix schedule meeting
  components/Confirmation.jsx
  components/Home.jsx
  components/MeetingsData.jsx
Labels: ready for review, forms

#211 replaced header tags with paragrapgh tags
  components/Confirmation.jsx
  components/Home.jsx
Labels: ready for review, forms

#212 changed breakpoints for input
  components/Profile.jsx
Labels: ready for review, profile

#210 Commented out 'forms' tab from navbar
  components/Navigation.jsx
Labels: ready for review, forms

#209 get 5 annoucements query
  pages/api/get5Announcements.js
Labels: backend

#231 Add the background of resource header
  components/Announcements.jsx
  components/AvailableForms.jsx
  components/Header.jsx
  pages/user/profile.js
  pages/user/resources.js
Labels: ready for review, resources

#240 deleted Toggle.jsx
  components/Toggle.jsx
Labels: ready for review, repository

#239 Error 400 and 500 pages + PageError comp
  components/PageError.jsx
  pages/user/error400.js
  pages/user/error500.js
Labels: ready for review

#237 deleted Register.jsx component
  components/Register.jsx
Labels: ready for review, login, repository

#238 iss 229 deleted hello.js component
  components/Register.jsx
Labels: ready for review, repository

#236 issue 201 making headers same size
  components/Announcements.jsx
  components/Meetings.jsx
Labels: ready for review

#243 mobile breakpoint and sizing for dashboard
  components/Home.jsx
  pages/user/dashboard.js
Labels: ready for review, dashboard

#241 Bobbyyy57/removeconfirmation
  components/Confirmation.jsx
Labels: ready for review, login, repository

#247 dropdown for major
  components/Profile.jsx
Labels: ready for review, profile

#246 changed border size
  components/Announcement.jsx
Labels: ready for review, dashboard

#250 Kninja99/bullet point fix
  components/Announcement.jsx
  components/Meeting.jsx
Labels: ready for review

#251 Archived forms
  components/forms/AvailableForm.jsx
  components/forms/AvailableForms.jsx
  components/forms/AvailableFormsArray.jsx
  components/forms/CompletedForm.jsx
  components/forms/CompletedForms.jsx
  components/forms/CompletedFormsArray.jsx
  components/forms/MockInterviewForm.jsx
  components/forms/MockInterviewFormDetails.jsx
  components/forms/MockinterviewFormData.jsx
  components/forms/ResumeReviewForm.jsx
  components/forms/ResumeReviewFormData.jsx
  components/forms/ResumeReviewFormDetails.jsx
  components/forms/SubmittedForm.jsx
  components/forms/SubmittedForms.jsx
  components/forms/SubmittedFormsArray.jsx
  pages/user/forms.js
Labels: ready for review

#253 centered no resources text on mobile
  components/Resources.jsx
Labels: resources

#252 Centered on Mobile
  components/Navigation.jsx
  components/Profile.jsx
Labels: profile

#255 made logo and hamburger smaller on mobile
  components/Navigation.jsx
Labels: ready for review, navigation

#254 Remove the scheduled meetings component
  components/Meeting.jsx
  components/Meetings.jsx
Labels: ready for review, dashboard, forms
